id = "yamura"
name = "Yamura"
version = "0.0.2"
schema_version = 1
authors = ["Yamura <yxmura@proton.me>"]
description = "Beautiful theme for Zed with great eye-soothing colors"
repository = "https://github.com/yxmura/yamura-zed-theme"
